# Generated by Django 4.2.1 on 2025-12-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0078_alter_competencesappreciations_evaluation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Ex: smtp.gmail.com', max_length=255, verbose_name='Serveur SMTP')),
                ('port', models.PositiveIntegerField(default=587, help_text='Port SMTP (587 pour TLS, 465 pour SSL)', verbose_name='Port')),
                ('use_tls', models.BooleanField(default=True, help_text='Cocher pour TLS, décocher pour SSL', verbose_name='Utiliser TLS')),
                ('username', models.CharField(help_text="Email ou nom d'utilisateur SMTP", max_length=255, verbose_name="Nom d'utilisateur")),
                ('password', models.CharField(help_text='Mot de passe SMTP', max_length=255, verbose_name='Mot de passe')),
                ('from_email', models.EmailField(help_text='Adresse email utilisée comme expéditeur par défaut', max_length=255, verbose_name='Email expéditeur')),
                ('is_active', models.BooleanField(default=False, help_text="Cocher pour activer l'envoi d'emails via SMTP", verbose_name="Activer l'envoi d'emails")),
            ],
            options={
                'verbose_name': 'Paramètres SMTP',
                'verbose_name_plural': 'Paramètres SMTP',
            },
        ),
        migrations.AlterField(
            model_name='competencesappreciations',
            name='evaluation',
            field=models.CharField(choices=[('-', 'Non évalué'), ('Maîtrise insuffisante', 'Maîtrise insuffisante'), ('Maîtrise partielle', 'Maîtrise partielle'), ('Très bonne maîtrise', 'Très bonne maîtrise'), ('Maîtrise satisfaisante', 'Maîtrise satisfaisante')], default='Non évalué', max_length=23),
        ),
        migrations.AlterField(
            model_name='projet',
            name='typeProjet',
            field=models.CharField(choices=[('TA', "Travail d'année"), ('PP', 'Projet pilote'), ('AUTRE', 'Projet divers'), ('PERS', 'Projet personnel'), ('COLL', 'Projet collectif')], max_length=60),
        ),
    ]
