# Generated by Django 4.2.1 on 2025-12-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0079_smtpsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='emails_bulletin',
            field=models.TextField(blank=True, help_text='Séparez plusieurs adresses par des virgules (ex: email1@exemple.com, email2@exemple.com)', null=True, verbose_name="Adresses email pour l'expédition du bulletin"),
        ),
    ]
