# Generated by Django 4.2.1 on 2025-12-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0085_discipline_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='miseenpagebulletin',
            name='par_defaut',
            field=models.BooleanField(default=False, help_text="Si coché, cette mise en page sera utilisée par défaut lors de l'édition des bulletins si aucune mise en page n'est spécifiée.", verbose_name='Mise en page par défaut'),
        ),
    ]
