# Generated by Django 4.2.1 on 2025-12-31 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletins', '0086_miseenpagebulletin_par_defaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvantPropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Contenu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avant_propos_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.eleve')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avant_propos_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.trimestre')),
            ],
            options={
                'verbose_name': 'Avant propos',
                'verbose_name_plural': 'Avant propos',
                'unique_together': {('eleve', 'trimestre')},
            },
        ),
    ]
