# Generated by Django 4.2.1 on 2025-12-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0087_avantpropos'),
    ]

    operations = [
        migrations.AddField(
            model_name='miseenpagebulletin',
            name='couleurAvantPropos',
            field=models.CharField(default='#ebebeb', max_length=10, verbose_name='Couleur avant propos'),
        ),
    ]
