# Generated by Django 4.2.1 on 2026-03-18 08:50

import bulletins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0089_discipline_activer_rang_max_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='miseenpagebulletin',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[bulletins.models.validate_file_size], verbose_name='Logo'),
        ),
    ]
