# Generated by Django 4.2.1 on 2026-03-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0090_add_logo_to_mise_en_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeuilsCompteurCaracteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_commentaire_warning', models.PositiveIntegerField(default=500, verbose_name='Seuil avertissement')),
                ('discipline_commentaire_danger', models.PositiveIntegerField(default=800, verbose_name='Seuil danger')),
                ('discipline_descriptif_warning', models.PositiveIntegerField(default=500, verbose_name='Seuil avertissement')),
                ('discipline_descriptif_danger', models.PositiveIntegerField(default=800, verbose_name='Seuil danger')),
                ('stage_descriptif_warning', models.PositiveIntegerField(default=500, verbose_name='Seuil avertissement')),
                ('stage_descriptif_danger', models.PositiveIntegerField(default=800, verbose_name='Seuil danger')),
                ('stage_appreciation_warning', models.PositiveIntegerField(default=500, verbose_name='Seuil avertissement')),
                ('stage_appreciation_danger', models.PositiveIntegerField(default=800, verbose_name='Seuil danger')),
                ('projet_descriptif_warning', models.PositiveIntegerField(default=500, verbose_name='Seuil avertissement')),
                ('projet_descriptif_danger', models.PositiveIntegerField(default=800, verbose_name='Seuil danger')),
                ('projet_appreciation_warning', models.PositiveIntegerField(default=500, verbose_name='Seuil avertissement')),
                ('projet_appreciation_danger', models.PositiveIntegerField(default=800, verbose_name='Seuil danger')),
                ('avis_college_warning', models.PositiveIntegerField(default=500, verbose_name='Seuil avertissement')),
                ('avis_college_danger', models.PositiveIntegerField(default=800, verbose_name='Seuil danger')),
            ],
            options={
                'verbose_name': 'Seuils compteur de caractères',
                'verbose_name_plural': 'Seuils compteur de caractères',
            },
        ),
    ]
