# Generated by Django 4.2.1 on 2026-03-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0091_seuilscompteurcaracteres'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='descriptif',
            field=models.TextField(blank=True, default=''),
        ),
    ]
