# Generated by Django 4.2.1 on 2026-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0092_add_descriptif_to_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='miseenpagebulletin',
            name='afficher_descriptif_classe',
            field=models.BooleanField(default=False, help_text="Si coché, le descriptif de la classe s'affiche à la suite de son nom dans l'en-tête du bulletin.", verbose_name='Afficher le descriptif de la classe'),
        ),
    ]
